presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-100-performance
    always_run: true
    skip_report: false
    max_concurrency: 12
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-e2e-scalability-common: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/perf-tests=master
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=120
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-nodes=100
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-100-performance
        - --tear-down-previous
        - --test=false
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=100
        - --test-cmd-args=--provider=gce
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-args=--testoverrides=./testing/density/100_nodes/override.yaml
        - --test-cmd-args=--testoverrides=./testing/prometheus/scrape-etcd.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=100m
        - --use-logexporter
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-e2e-gce-big-performance
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-e2e-scalability-common: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/perf-tests=master
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=270
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env=HEAPSTER_MACHINE_TYPE=n1-standard-4
        - --extract=local
        - --gcp-nodes=500
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-a
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-big-performance
        - --tear-down-previous
        - --test=false
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=500
        - --test-cmd-args=--provider=gce
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-args=--testoverrides=./testing/prometheus/scrape-etcd.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=240m
        - --use-logexporter
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-e2e-gce-large-performance
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-e2e-scalability-common: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/perf-tests=master
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=570
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env=HEAPSTER_MACHINE_TYPE=n1-standard-8
        - --extract=local
        - --gcp-nodes=2000
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-a
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-large-performance
        - --test=false
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=2000
        - --test-cmd-args=--provider=gce
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-args=--testoverrides=./testing/density/2000_nodes/override.yaml
        - --test-cmd-args=--testoverrides=./testing/prometheus/scrape-etcd.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=540m
        - --use-logexporter
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-kubemark-e2e-gce-big
    always_run: true
    skip_report: false
    max_concurrency: 12
    skip_branches:
    - release-\d+\.\d+  # per-release image
    annotations:
      fork-per-release: "true"
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
      preset-e2e-kubemark-common: "true"
      preset-e2e-kubemark-gce-big: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/perf-tests=master"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=120"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-master-size=n1-standard-4
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=7
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=500
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-big
        - --tear-down-previous
        - --test=false
        - --test_args=--ginkgo.focus=xxxx
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=500
        - --test-cmd-args=--provider=kubemark
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-args=--testoverrides=./testing/load/kubemark/500_nodes/override.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=100m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        resources:
          requests:
            memory: "6Gi"
        securityContext:
          privileged: true # TODO(fejta): https://github.com/kubernetes/kubernetes/issues/76484
  - name: pull-kubernetes-kubemark-e2e-gce-scale
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
      preset-e2e-kubemark-common: "true"
      preset-e2e-kubemark-gce-scale: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/perf-tests=master"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=1220"
        - --scenario=kubernetes_e2e
        - --
        - --build
        - --cluster=
        - --extract=local
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=82
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=5000
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-scale
        - --test=false
        - --test_args=--ginkgo.focus=xxxx
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=5000
        - --test-cmd-args=--provider=kubemark
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=1200m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        resources:
          requests:
            memory: "6Gi"
  kubernetes/perf-tests:
  - name: pull-perf-tests-clusterloader2
    always_run: true
    skip_report: false
    max_concurrency: 2
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-e2e-scalability-common: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=master
        - --repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=120
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-nodes=100
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-perf-tests-clusterloader2
        - --tear-down-previous
        - --test=false
        - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
        - --test-cmd-args=cluster-loader2
        - --test-cmd-args=--nodes=100
        - --test-cmd-args=--provider=gce
        - --test-cmd-args=--report-dir=/workspace/_artifacts
        - --test-cmd-args=--testconfig=testing/density/config.yaml
        - --test-cmd-args=--testconfig=testing/load/config.yaml
        - --test-cmd-args=--testoverrides=./testing/density/100_nodes/override.yaml
        - --test-cmd-args=--testoverrides=./testing/prometheus/scrape-etcd.yaml
        - --test-cmd-name=ClusterLoaderV2
        - --timeout=100m
        - --use-logexporter
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
        resources:
          requests:
            memory: "6Gi"
  - name: pull-perf-tests-clusterloader2-kubemark
    always_run: true
    skip_report: false
    max_concurrency: 2
    branches:
      - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
      preset-e2e-kubemark-common: "true"
      preset-e2e-kubemark-gce-big: "true"
    spec:
      containers:
        - args:
            - --root=/go/src
            - --repo=k8s.io/kubernetes=master
            - --repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)
            - --repo=k8s.io/release
            - --service-account=/etc/service-account/service-account.json
            - --upload=gs://kubernetes-jenkins/pr-logs
            - --timeout=120
            - --scenario=kubernetes_e2e
            - --
            - --build=bazel
            - --cluster=
            - --extract=local
            - --gcp-master-size=n1-standard-4
            - --gcp-node-size=n1-standard-8
            - --gcp-nodes=7
            - --gcp-project=k8s-presubmit-scale
            - --gcp-zone=us-east1-b
            - --kubemark
            - --kubemark-nodes=500
            - --provider=gce
            - --stage=gs://kubernetes-release-pull/ci/pull-perf-tests-clusterloader2-kubemark
            - --tear-down-previous
            - --test=false
            - --test_args=--ginkgo.focus=xxxx
            - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
            - --test-cmd-args=cluster-loader2
            - --test-cmd-args=--nodes=500
            - --test-cmd-args=--provider=kubemark
            - --test-cmd-args=--report-dir=/workspace/_artifacts
            - --test-cmd-args=--testconfig=testing/density/config.yaml
            - --test-cmd-args=--testconfig=testing/load/config.yaml
            - --test-cmd-args=--testoverrides=./testing/load/kubemark/500_nodes/override.yaml
            - --test-cmd-name=ClusterLoaderV2
            - --timeout=100m
            - --use-logexporter
          image: gcr.io/k8s-testimages/kubekins-e2e:v20190528-b03896b-master
          resources:
            requests:
              memory: "6Gi"
